#!/usr/bin/env php
<?php

namespace Sparkfabrik\GitlabCiClient;

require __DIR__ . '/../vendor/autoload.php';

use Gitlab\Client;
use Symfony\Component\Console\Application;


$app = new Application('Gitlab actions', '0.0.1');
$app->add(new GitlabActionsCommand(new Client()));
$app->setdefaultCommand('gitlab:actions', TRUE);
$app->run();

