name: Docker
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: gitlab-ci-client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        env:
          GITLAB_PRIVATE_TOKEN: Dummy token
          CI_SERVER_URL: https://gitlab.dummy-site.com
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: mbstring
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push images to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker buildx build --push . --platform "linux/amd64,linux/arm64" \
            --tag $IMAGE_ID:latest \
